version: '3'

services:
  trezor-remote-signer:
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    devices:
      - /dev/bus/usb/003/016
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/remote-signer.sh
    # restart: on-failure

  tezos-client:
    build: ./tezos-client
    hostname: tezos-client
    environment:
      - ADDRESS=zeronet.simplestaking.com
      - PORT=3000
    volumes:
      - ./tezos-client:/var/tezos-client
    entrypoint: /var/tezos-client/tezos-client.sh
    depends_on:
      - trezor-remote-signer
    # restart: on-failure

  # tezos-endorser:
  #   build: ./tezos-endorser
  #   hostname: tezos-endorser
  #   volumes:
  #     - ./tezos-endorser:/var/tezos-endorser
  #   entrypoint: /var/tezos-endorser/tezos-endorser.sh
  #   depends_on:
  #     - trezor-remote-signer
  #   # restart: on-failure


# 0. running tezos node zeronet.simpelstaking.com

# 1. run remote_signer and listen 
# 2. check if trezor is flashed

# 3. exec tezos-client from docker 

# 4. get tezos addrres from trezor 

# 5. download faucet 
# 6. send xtz to address

# 7. import remote keys to tezos-client
# 8. register delegate 
# 9. start baking