version: '3'

services:

  trezor-signer:
    image: simplestakingcom/trezor-signer
    build: ./trezor-signer
    hostname: trezor-signer
    devices:
      # lsusb -d 1209:53c1
      - ${TREZOR_USB_PATH}
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-signer:/var/trezor-signer
    logging:
        driver: none

  # tezos-endorser:
  #   image: simplestakingcom/tezos-endorser
  #   build: ./tezos-endorser
  #   hostname: tezos-endorser
  #   env_file:
  #     - ./config.baking.env
  #   volumes:
  #     - ./tezos-endorser:/var/tezos-endorser
  #   entrypoint: /var/tezos-endorser/tezos-endorser.sh
  #   depends_on:
  #     - trezor-signer
  #   restart: on-failure

  tezos-baker:
    build: ./tezos-baker
    hostname: tezos-baker
    env_file:
      - ./config.baking.env
    volumes:
      - ./tezos-baker:/var/tezos-baker
      - ${TEZOS_NODE_DATA_PATH}:/var/tezos-node
    entrypoint: /var/tezos-baker/tezos-baker.sh
    depends_on:
      - trezor-signer
      # - tezos-endorser
    restart: on-failure