version: '3'

services:
  
  trezor-remote-signer:
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    devices:
      # lsusb -d 1209:53c1
      - ${TREZOR_USB_PATH}
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/remote-signer.sh

  tezos-client:
    build: ./tezos-client
    hostname: tezos-client
    env_file:
      - ./docker-compose.initialize.env
    volumes:
      - ./tezos-client:/var/tezos-client
    entrypoint: /var/tezos-client/tezos-client.sh
    depends_on:
      - trezor-remote-signer








