version: '3'

services:
  trezor-remote-signer:
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/entrypoint.sh
    # devices:
    #   - /dev/ttyUSB0
    # restart: on-failure

  tezos-client:
    image: tezos/tezos:zeronet
    hostname: tezos-client
    entrypoint: /var/tezos-client/entrypoint.sh
    volumes:
      - ./tezos-client:/var/tezos-client
    restart: on-failure

# 0. running tezos node zeronet.simpelstaking.com
# 1. run remote_signer and listen 
# 2. check if trezor is flashed

# 3. exec tezos-client from docker 

# 4. get tezos addrress from trezor 

# 5. download faucet 
# 6. send xtz to address

# 7. import remote keys to tezos-client
# 8. register delegate 
# 9. start baking


