version: '3'

services:

  trezor-remote-signer:
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    devices:
    - /dev/bus/usb/003/005
    # network_mode: "host"
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/remote-signer.sh
    # depends_on:
    #   - trezor-baking-firmware

  tezos-endorser:
    build: ./tezos-endorser
    hostname: tezos-endorser
    # network_mode: "host"
    volumes:
      - ./tezos-endorser:/var/tezos-endorser
    entrypoint: /var/tezos-endorser/tezos-endorser.sh
    depends_on:
      - trezor-remote-signer
    # restart: on-failure

  # tezos-baker:
  #   build: ./tezos-baker
  #   hostname: tezos-baker
  #   volumes:
  #     - ./tezos-baker:/var/tezos-baker
  #     - /home/juchuchu/.tezos-node:/var/tezos-node
  #   entrypoint: /var/tezos-baker/tezos-baker.sh
  #   depends_on:
  #     - trezor-remote-signer
  #   # restart: on-failure