version: '3'

services:

  trezor-remote-signer:
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    devices:
      # lsusb -d 1209:53c1
      - ${TREZOR_USB_PATH}
    # network_mode: "host"
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/remote-signer.sh

  tezos-client:
    build: ./tezos-client
    hostname: tezos-client
    environment:
      - ADDRESS=zeronet.simplestaking.com
      - PORT=3000
    volumes:
      - ./tezos-client:/var/tezos-client
    entrypoint: /var/tezos-client/tezos-client.sh
    depends_on:
      - trezor-remote-signer








