version: '3'

services:

  # trezor-baking-firmware:
  #   build: ./trezor-baking-firmware
  #   hostname: trezor-baking-firmware
  #   devices:
  #     # lsusb -d 1209:53c1
  #     - /dev/bus/usb/003/010
  #   volumes:
  #     - ./trezor-baking-firmware:/var/trezor-baking-firmware
  #   entrypoint: /var/trezor-baking-firmware/trezor-baking-firmware.sh

  trezor-remote-signer:
    build: ./trezor-remote-signer
    hostname: trezor-remote-signer
    # devices:
    # - /dev/bus/usb/003/012
    network_mode: "host"
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-remote-signer:/var/trezor-remote-signer
    entrypoint: /var/trezor-remote-signer/remote-signer.sh
    # depends_on:
    #   - trezor-baking-firmware

  # tezos-client:
  #   build: ./tezos-client
  #   hostname: tezos-client
  #   environment:
  #     - ADDRESS=zeronet.simplestaking.com
  #     - PORT=3000
  #   volumes:
  #     - ./tezos-client:/var/tezos-client
  #   entrypoint: /var/tezos-client/tezos-client.sh
  #   depends_on:
  #     - trezor-remote-signer

  tezos-endorser:
    build: ./tezos-endorser
    hostname: tezos-endorser
    network_mode: "host"
    volumes:
      - ./tezos-endorser:/var/tezos-endorser
    entrypoint: /var/tezos-endorser/tezos-endorser.sh
    depends_on:
      - trezor-remote-signer
    # restart: on-failure

  # tezos-baker:
  #   build: ./tezos-baker
  #   hostname: tezos-baker
  #   volumes:
  #     - ./tezos-baker:/var/tezos-baker
  #     - /home/juchuchu/.tezos-node:/var/tezos-node
  #   entrypoint: /var/tezos-baker/tezos-baker.sh
  #   depends_on:
  #     - trezor-remote-signer
  #   # restart: on-failure







# 0. running tezos node zeronet.simpelstaking.com

# 1. run remote_signer and listen 
# 2. check if trezor is flashed

# 3. exec tezos-client from docker 

# 4. get tezos addrres from trezor 

# 5. download faucet 
# 6. send xtz to address

# 7. import remote keys to tezos-client
# 8. register delegate 
# 9. start baking