version: '3'

services:
  
  trezor-signer:
    image: simplestakingcom/trezor-signer
    build: ./trezor-signer
    hostname: trezor-signer
    devices:
      # lsusb -d 1209:53c1
      - ${TREZOR_USB_PATH}
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-signer:/var/trezor-signer
    # environment:
    #   - LOGLEVEL=DEBUG
    # logging:
    #     driver: none

  tezos-client:
    build: ./tezos-client
    hostname: tezos-client
    env_file:
      - ./config.initialize.env
    volumes:
      - ./tezos-client:/var/tezos-client
    entrypoint: /var/tezos-client/tezos-client.sh
    depends_on:
      - trezor-signer