version: '3'

services:
  
  trezor-signer:
    image: simplestakingcom/trezor-signer
    build: ./trezor-signer
    hostname: trezor-signer
    devices:
      # lsusb -d 1209:53c1
      - ${TREZOR_USB_PATH}
    ports:
    - "5000:5000"
    volumes:
      - ./trezor-signer:/var/trezor-signer
    logging:
        driver: none

  tezos-client:
    image: simplestakingcom/tezos-client
    build: ./tezos-client
    hostname: tezos-client
    env_file:
      - ./config.baking.env
    volumes:
      - ./tezos-client:/var/tezos-client
    entrypoint: /var/tezos-client/tezos-client-baking-stop.sh
    depends_on:
      - trezor-signer